### ISSUE TITLE
缺少glibc

### ISSUE THREAD

**Issue by sst4rb0y** [Leviathan1995/spleen#3]
输出如下：
 % ./spleen-server -c .server.json
./spleen-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./spleen-server)
./spleen-server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./spleen-server)

**Comment by Leviathan1995** [comment]
装一个 GLIBC_2.32 就好了

**Comment by sst4rb0y** [comment]
> 装一个 GLIBC_2.32 就好了

您好，我升级了ubuntu的LTS版本到了22，成功了。感谢回复。
